### ISSUE TITLE
Allow passing named build context to docker

### ISSUE THREAD

**Issue by krassowski** [jamsocket/jamsocket-deploy-action#3]
Currently the action only allows to pass a single `context`:

https://github.com/jamsocket/jamsocket-deploy-action/blob/ec15e07b5e73759a94123570e44e68f4e905aca0/action.yml#L64-L67

But the underlying docker action (https://github.com/docker/build-push-action?tab=readme-ov-file) allows to pass multiple named contexts, e.g.:

```
      - name: Build
        uses: docker/build-push-action@v6
        with:
          build-contexts: |
            alpine=docker-image://my-base-image:latest            
          tags: myimage:latest
```

(from https://docs.docker.com/build/ci/github-actions/named-contexts/)

Can jamsocket-deploy-action support passing `build-contexts` in addition to `context`?
